name = "drn"
description = "Theme built for drn.ie"
license = "MIT"
homepage = "https://github.com/darrenmeehan/drn-ie"
min_version = "1.0.0"
demo = "https://drn.ie"

[extra]
greeting = "Hello!"

iam = "I am"

links = [
    { title = "E-Mail", url = "mailto:mail@example.org", iconset = "fas", icon = "envelope" },
    { title = "GitHub", url = "https://github.com", icon = "github" },
]

[extra.author]
name = "Hallo"

[extra.theme]
background = "#6FCDBD"
foreground = "#FFF"
hover = "#333"

[author]
name = "Jan Baudisch"
homepage = "https://janbaudisch.dev"

[original]
author =  "Emiel Hollander"
homepage = "https://themes.gohugo.io/theme/hallo-hugo/"
repo = "https://github.com/EmielH/hallo-hugo"
