# The URL the site will be built for
# base_url = "https://drn.ie"
base_url = "https://drn-ie.fly.dev"
# base_url = "http://localhost:3001"

title = "Darren Meehan's personal site"
description = "Public site of Darren Meehan"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "drn"

render_emoji = true

paths_keep_dates = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
greeting = "Hello!"

iam = "My name is"

links = [
    { title = "E-Mail", url = "mailto:hi@drn.ie", iconset = "fas", icon = "envelope" },
    { title = "GitHub", url = "https://github.com/darrenmeehan", icon = "github" },
    { title = "Twitter", url = "https://twitter.com/darrenmeehan", icon = "twitter" },
    { title = "LinkedIn", url = "https://www.linkedin.com/in/darrenmeehan/", icon = "linkedin" },
    { title = "Keybase", url = "https://keybase.io/darrenmeehan", icon = "keybase" }
]

[extra.author]
name = "Darren Meehan"

[extra.theme]
background = "#000"
foreground = "#FFF"
hover = "#333"

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"
