# fly.toml app configuration file generated for drn-ie on 2024-05-21T20:51:49+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'drn-ie'
# Madrid
primary_region = 'mad'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[build]
  dockerfile = 'Dockerfile'

[[vm]]
  size = 'shared-cpu-1x'

# [processes]
# builder = ""
# server = ""

# [[services]]
# processes = ["server"]
