backend:
  name: git-gateway
  branch: master
media_folder: "static/images"
site_url: https://drn.ie

media_library:
  name: cloudinary
  config:
    cloud_name: difx30h6p # This is a public value
    api_key: 629385684364377 # This is a public key

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    label_singular: "Post"
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    filter: {field: "visible", value: true}
    fields: # The fields for each document, usually in front matter
      - {label: "Template", name: "template", widget: "hidden", default: "blog-page.html"}
      - {label: "Visible", name: "visible", widget: hidden, default: true}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Photos"
        name: "extra"
        widget: "object"
        summary: "Single or several images to include"
        fields:
          - label: "Images"
            name: "images"
            widget: "image"
            allow_multiple: true
            required: true
            media_library:
              config:
                multiple: true
  - name: "photos"
    label: "Photos" # Used in the UI
    label_singular: "Photo"
    folder: "content/photos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    filter: {field: "visible", value: true}
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "photo.html"}
      - {label: "Visible", name: "visible", widget: hidden, default: true}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}   
      - label: "Photos"
        name: "extra"
        widget: "object"
        summary: "Single or several images to include"
        fields:
          - label: "Images"
            name: "images"
            widget: "image"
            allow_multiple: true
            required: true
            media_library:
              config:
                multiple: true
  - name: "dives"
    label: "Dives"
    label_singular: "Dive"
    folder: "content/dives"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter: {field: "visible", value: true}
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "dive.html"}
      - {label: "Visible", name: "visible", widget: hidden, default: true}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Dive Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"} 
      - label: "Details"
        name: "extra"
        widget: "object"
        summary: "Dive Details"
        fields:
          - {label: "Dive Site", name: "site", widget: "string"}
          - label: "Images"
            name: "images"
            widget: "image"
            allow_multiple: true
            required: false
            media_library:
              config:
                multiple: true
          - {label: "Fish", name: "fish", widget: "list" }
          - {label: "Location", name: "location", widget: "map", required: false }
          - {label: "Depth", name: "depth", hint: "In metres", widget: "number", value_type: "float", min: 0, max: 40, default: 10}
          - {label: "Duration", name: "duration", hint: "In minutes", widget: "number", value_type: "int", min: 0, max: 120, default: 30}
          - {label: "Visibility", name: "visibility", hint: "In metres", widget: "number", value_type: "int", min: 0, max: 100, default: 10}
          - {label: "Current", name: "current", widget: "string"}
          - {label: "Dive Type", name: "dive_type", widget: "string"}
          - {label: "Dive Centre", name: "dive_centre", widget: "string"}
          - {label: "Dive Centre Website", name: "dive_centre_website", widget: "string", required: false}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/_index.md"
        fields:
          - {label: "Template", name: "template", widget: "hidden", default: "index.html"}
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - label: "About"
        name: "about"
        file: "content/about/_index.md"
        fields:
          - {label: "Template", name: "template", widget: "hidden", default: "section.html"}
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - label: "About Site"
        name: "about-site"
        file: "content/about/site/_index.md"
        fields:
          - {label: "Template", name: "template", widget: "hidden", default: "section.html"}
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
