name: Build Site
on:
    push:
        branches:
            - main
env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        name: Build content
        runs-on: ubuntu-latest
        container: rustlang/rust:nightly-bookworm
        steps:
            - name: Get current date
              id: date
              run: echo "::set-output name=date::$(date +'%Y-%m-%d')"          
            - uses: actions/checkout@v3
            - name: Install zola
              run: cargo install --git https://github.com/getzola/zola/
            - name: Build site
              run: zola build
            - name: Archive site
              run: tar -czvf drn-ie-v${{ steps.date.outputs.date }}.tar.gz public
            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                files: drn-ie-v${{ steps.date.outputs.date }}.tar.gz
                tag_name: ${{ steps.date.outputs.date }}
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run: flyctl deploy --remote-only
              env:
                FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
