name: Build and Deploy Site
on:
  push:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build content
    runs-on: ubuntu-latest
    container: rustlang/rust:nightly-bookworm
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
